export const events = [
    {
        "date": "2024-02-24",
        "title": "Sustainable Finance Market Game",
        "description": "We will be going over sustainable finance with a focus on the impacts on the energy industry and playing a Stock Market game where we will have the chance to \"invest\" 100$ into different investment opportunities and then track those investments over a simulated year to see how different investments are impacted by world events!",
        "imageFile": "sustainable-finance.webp",
        "location": "EV1 350 & Microsoft Teams",
    },
    {
        "date": "2024-02-23",
        "title": "Sustainable Finance Market Game",
        "description": "We will be going over sustainable finance with a focus on the impacts on the energy industry and playing a Stock Market game where we will have the chance to \"invest\" 100$ into different investment opportunities and then track those investments over a simulated year to see how different investments are impacted by world events!",
        "imageFile": "sustainable-finance.webp",
        "location": "EV1 350 & Microsoft Teams",
    },
    {
        "date": "2024-02-22",
        "title": "Sustainable Finance Market Game",
        "description": "We will be going over sustainable finance with a focus on the impacts on the energy industry and playing a Stock Market game where we will have the chance to \"invest\" 100$ into different investment opportunities and then track those investments over a simulated year to see how different investments are impacted by world events!",
        "imageFile": "sustainable-finance.webp",
        "location": "EV1 350 & Microsoft Teams",
    },
    {
        "date": "2023-11-21",
        "title": "Sustainable Finance Market Game",
        "description": "We will be going over sustainable finance with a focus on the impacts on the energy industry and playing a Stock Market game where we will have the chance to \"invest\" 100$ into different investment opportunities and then track those investments over a simulated year to see how different investments are impacted by world events!",
        "imageFile": "sustainable-finance.webp",
        "location": "EV1 350 & Microsoft Teams",
    },
    {
        "date": "2023-10-25",
        "title": "Renewable Energy Careers Panel",
        "description": "UWEN hosted an Energy Careers Panel. Four amazing panelists participated and shared their experiences in the energy industry with members and answered questions about getting into the energy world. There was free pizza for all in person attendees! The panelists provided us with many resources and provided their contact information for anyone with further questions.",
        "imageFile": "careers-panel.webp",
        "location": "",
    },
    {
        "date": "2023-10-05",
        "title": "Enerchat - Dr.Bronwyn Lazowski",
        "description": "Returning for her second EnerChat, Dr.Bronwyn Lazowski is a Senior Policy Advisor for the Office of Energy Research & Development. She is a UWaterloo Alumni and has earned her PhD in Geography and Environmental Management where her research focused on residential electricity conservation and demand management through smart grid technologies, programs and policies! During the event, she talked about her current work as she is leading at Natural Resources Canada. She also talked about career opportunities in the energy sector for research related to public policy. Viewers learned a lot about Canada's grid modernization future while enjoying timbits and coffee. The event ended with a short Q&A where Bronwyn provided a lot more insight.",
        "imageFile": "enerchat.webp",
        "location": "",
    },
    {
        "date": "2023-06-20",
        "title": "Fuel Cell Enerchat with Ballard Power Systems",
        "description": "Sumit Kundu is a University of Waterloo graduate who is now an industry professional at Ballard Power Systems working as the manager of Stack Test Engineering. He graduated from Waterloo with a PhD in chemical engineering and is now working in the hydrogen fuel cell industry where he has worked on research, product development, and the testing and characterization of fuel cell technologies.",
        "imageFile": "ballard.webp",
        "location": "",
    },
    {
        "date": "2023-03-28",
        "title": "Enerchat - Professor Claudio Canizares",
        "description": "Professor Claudio Canizares is the Associate Director for the Waterloo Institute for Sustainable Energy (WISE) and a graduate professor from the Department of Electrical and Computer Engineering. He came to present his research at UWEN's first Enerchat of the Winter 2023 term, the presentation was held in person in QNC 1506 with free coffee and timbits for participants!It was also accessible online via Microsoft Teams  Dr.Claudio Canizares discussed his research on microgrids as well as the student internship opportunities offered by WISE through AE4H. He offered a detailed background on how power grids work and then expanded to the application of microgrids in northern communities in Canada. The 30-minute presentation was followed by an engaging Q&A session where students were able to ask questions to Dr.Claudio Canizares about the future of grids and the energy sector.",
        "imageFile": "enerchat-claudio.webp",
        "location": "",
    },
    {
        "date": "2023-03-29",
        "title": "Clubs and Communities Fair",
        "description": "UWEN held a booth at Envigorate's Clubs and Communities Fair to raise awareness about initiatives in the Renewable Energy space and connect with students and other regional groups!",
        "imageFile": "clubs-and-communities.webp",
        "location": "",
    },
];
